[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 4

[rpc_endpoints]
mumbai = "${MUMBAI_RPC}"

[polyscan]
mumbai = { key = "${POLYGONSCAN_API}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config